# Deploy each tag to its own gh-pages sub-branch
name: Deploy tagged version to Pages

on:
  push:
    tags:
      - '*'  # Trigger on any tag

permissions:
  contents: write  # Required to push to gh-pages branches
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine Tag
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build or Prepare Site
        run: |
          # Replace this with your build command if you have one
          # e.g., npm run build
          echo "Copying site for deployment..."
          mkdir -p site
          cp -r * site/

      - name: Push to gh-pages/<tag>
        run: |
          cd site
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git checkout -b gh-pages/${TAG_NAME}
          git add .
          git commit -m "Deploy ${TAG_NAME}"
          git push -f origin gh-pages/${TAG_NAME}

      - name: Set GitHub Pages branch for tag
        uses: actions/github-script@v6
        with:
          script: |
            const tag = process.env.TAG_NAME;
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pages: {
                source: {
                  branch: `gh-pages/${tag}`,
                  path: "/"
                }
              }
            });
