# Deploy each tag to a subfolder on GitHub Pages
name: Deploy tagged version to GitHub Pages

on:
  push:
    tags:
      - '*'  # Trigger on any tag
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Determine the tag
      - name: Determine Tag
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      # 3. Prepare site files
      - name: Prepare site for deployment
        run: |
          mkdir -p site
          for f in *; do
            if [[ "$f" != "site" && "$f" != ".github" && "$f" != "LICENSE" && "$f" != "README.md" ]]; then
              cp -r "$f" site/
            fi
          done

      # 4. Organize versioned folder
      - name: Move site into tag folder
        run: |
          mkdir -p deploy
          mkdir -p deploy/$TAG_NAME
          cp -r site/* deploy/$TAG_NAME/

      # 5. Upload artifact for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # 7. Optional: set Pages branch (already handled by deploy-pages)
      - name: Show deployed URL
        run: echo "Site deployed under folder /$TAG_NAME/"
